services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: always
    ports:
      - 3005:3005
    networks:
      - audiobookshelf_tracker
    volumes:
      - ./data:/data
    environment:
      - CLIENT_PORT=3000
      - SERVER_PORT=3005
      - PASSWORD= # admin password, change this
      - JWT_SECRET= # random salt, change this
      - ABS_URL= # Audiobookshelf server, e.g.: http://192.168.0.129:13378
      - ABS_TOKEN= # Your Audiobookshelf admin token

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - audiobookshelf_tracker
    environment:
      - CLIENT_PORT=3000
      - SERVER_PORT=3005

networks:
  audiobookshelf_tracker:
    external: true
