name: Build and push Docker images

on:
  push:
    branches:
      - main

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker tag audiobookshelf-tracker-server ghcr.io/${{ github.repository_owner }}/audiobookshelf-tracker-server:latest
          docker tag audiobookshelf-tracker-client ghcr.io/${{ github.repository_owner }}/audiobookshelf-tracker-client:latest
          docker push ghcr.io/${{ github.repository_owner }}/audiobookshelf-tracker-server:latest
          docker push ghcr.io/${{ github.repository_owner }}/audiobookshelf-tracker-client:latest



